export const productosDeViaje = [
    {
      id: 1,
      destino: "Cancún, México",
      características: "Playa, cultura, actividades acuáticas",
      días: 7,
      precio: 1200,
      imagen: "https://picsum.photos/200/300",
      hoteles: ["Hotel Riu Cancun", "Grand Fiesta Americana", "The Royal Sands"],
      todoIncluido: true,
    },
    {
      id: 2,
      destino: "Paris, Francia",
      características: "Cultura, historia, museos, gastronomía",
      días: 5,
      precio: 1500,
      imagen: "https://picsum.photos/200/300",
      hoteles: ["Le Meurice", "Hotel Plaza Athénée", "Hôtel de Crillon"],
      todoIncluido: false,
    },
    {
      id: 3,
      destino: "Roma, Italia",
      características: "Historia, arquitectura, gastronomía",
      días: 6,
      precio: 1300,
      imagen: "https://picsum.photos/200/300",
      hoteles: ["Hotel Quirinale", "The St. Regis Rome", "Hotel Artemide"],
      todoIncluido: false,
    },
    {
      id: 4,
      destino: "Bali, Indonesia",
      características: "Playa, relax, cultura, naturaleza",
      días: 10,
      precio: 1700,
      imagen: "https://picsum.photos/200/300",
      hoteles: [
        "Four Seasons Resort Bali",
        "The Legian Bali",
        "Mandapa, a Ritz-Carlton Reserve",
      ],
      todoIncluido: true,
    },
    {
      id: 5,
      destino: "Nueva York, Estados Unidos",
      características: "Cultura, compras, entretenimiento, gastronomía",
      días: 4,
      precio: 1000,
      imagen: "https://picsum.photos/200/300",
      hoteles: [
        "The Plaza Hotel",
        "Four Seasons Hotel New York",
        "The Greenwich Hotel",
      ],
      todoIncluido: false,
    },
    {
      id: 6,
      destino: "Tokio, Japón",
      características: "Cultura, tecnología, gastronomía",
      días: 8,
      precio: 2000,
      imagen: "https://picsum.photos/200/300",
      hoteles: [
        "Park Hyatt Tokyo",
        "The Peninsula Tokyo",
        "Mandarin Oriental Tokyo",
      ],
      todoIncluido: false,
    },
    {
      id: 7,
      destino: "Dubai, Emiratos Árabes Unidos",
      características: "Lujo, compras, cultura, modernidad",
      días: 5,
      precio: 2500,
      imagen: "https://picsum.photos/200/300",
      hoteles: [
        "Burj Al Arab Jumeirah",
        "Atlantis The Palm",
        "Armani Hotel Dubai",
      ],
      todoIncluido: true,
    },
    {
      id: 8,
      destino: "Maldivas",
      características: "Playa, relax, lujo, naturaleza",
      días: 7,
      precio: 3000,
      imagen: "https://picsum.photos/200/300",
      hoteles: [
        "Soneva Fushi",
        "One&Only Reethi Rah",
        "The St. Regis Maldives Vommuli Resort",
      ],
      todoIncluido: true,
    },
    {
      id: 9,
      destino: "Londres, Reino Unido",
      características: "Historia, cultura, museos, entretenimiento",
      días: 6,
      precio: 1100,
      imagen: "https://picsum.photos/200/300",
      hoteles: [
        "The Ritz London",
        "The Langham",
        "Shangri-La Hotel at The Shard",
      ],
      todoIncluido: false,
    },
    {
      id: 10,
      destino: "Ámsterdam, Países Bajos",
      características: "Cultura, historia, arquitectura, canales",
      días: 4,
      precio: 850,
      imagen: "https://picsum.photos/200/300",
      hoteles: [
        "Conservatorium Hotel",
        "The Dylan Amsterdam",
        "Pulitzer Amsterdam",
      ],
      todoIncluido: false,
    },
    {
      id: 11,
      destino: "Madrid, España",
      características: "Cultura, historia, gastronomía, entretenimiento",
      días: 5,
      precio: 900,
      imagen: "https://picsum.photos/200/300",
      hoteles: [
        "Hotel Ritz Madrid",
        "Gran Meliá Palacio de los Duques",
        "The Westin Palace",
      ],
      todoIncluido: false,
    },
    {
      id: 12,
      destino: "Barcelona, España",
      características: "Cultura, arquitectura, playa, gastronomía",
      días: 5,
      precio: 950,
      imagen: "https://picsum.photos/200/300",
      hoteles: ["Hotel Arts Barcelona", "W Barcelona", "Majestic Hotel & Spa"],
      todoIncluido: false,
    },
    {
      id: 13,
      destino: "Cabo San Lucas, México",
      características: "Playa, relax, actividades acuáticas",
      días: 7,
      precio: 1300,
      imagen: "https://picsum.photos/200/300",
      hoteles: [
        "The Resort at Pedregal",
        "Waldorf Astoria Los Cabos",
        "Grand Velas Los Cabos",
      ],
      todoIncluido: true,
    },
    {
      id: 14,
      destino: "Sydney, Australia",
      características: "Playa, cultura, naturaleza, entretenimiento",
      días: 6,
      precio: 1800,
      imagen: "https://picsum.photos/200/300",
      hoteles: [
        "Park Hyatt Sydney",
        "The Langham Sydney",
        "Shangri-La Hotel Sydney",
      ],
      todoIncluido: false,
    },
    {
      id: 15,
      destino: "Lima, Perú",
      características: "Cultura, gastronomía, historia",
      días: 5,
      precio: 1100,
      imagen: "https://picsum.photos/200/300",
      hoteles: ["Belmond Miraflores Park", "JW Marriott Hotel Lima", "Hotel B"],
      todoIncluido: false,
    },
    {
      id: 16,
      destino: "Cusco, Perú",
      características: "Cultura, historia, naturaleza, aventura",
      días: 6,
      precio: 1200,
      imagen: "https://picsum.photos/200/300",
      hoteles: [
        "Belmond Palacio Nazarenas",
        "Palacio del Inka",
        "Hotel Monasterio",
      ],
      todoIncluido: false,
    },
    {
      id: 17,
      destino: "Kioto, Japón",
      características: "Cultura, historia, templos, jardines",
      días: 5,
      precio: 1300,
      imagen: "https://picsum.photos/200/300",
      hoteles: [
        "The Ritz-Carlton Kyoto",
        "Four Seasons Hotel Kyoto",
        "Hyatt Centric Kyoto",
      ],
      todoIncluido: false,
    },
    {
      id: 18,
      destino: "Buenos Aires, Argentina",
      características: "Cultura, gastronomía, historia, tango",
      días: 5,
      precio: 950,
      imagen: "https://picsum.photos/200/300",
      hoteles: [
        "Alvear Palace Hotel",
        "Faena Hotel Buenos Aires",
        "Palacio Duhau - Park Hyatt Buenos Aires",
      ],
      todoIncluido: false,
    },
    {
      id: 19,
      destino: "Costa Rica",
      características: "Naturaleza, ecoturismo, aventura",
      días: 10,
      precio: 2200,
      imagen: "https://picsum.photos/200/300",
      hoteles: [
        "Four Seasons Resort Costa Rica",
        "Andaz Costa Rica Resort",
        "The Springs Resort and Spa",
      ],
      todoIncluido: true,
    },
    {
      id: 20,
      destino: "Tulum, México",
      características: "Playa, relax, naturaleza, cultura",
      días: 7,
      precio: 1400,
      imagen: "https://picsum.photos/200/300",
      hoteles: ["Azulik", "Be Tulum", "Coqui Coqui"],
      todoIncluido: true,
    },
  ];

  export const getAllProducts = ()=>{
    return productosDeViaje;
  }